---

rancher_url: "{{ lookup('env','RANCHER_ECR') }}"

rancher_access_key: "{{ lookup('env','RANCHER_ENV_PROD_ACCESS_KEY') }}"
rancher_secret_key: "{{ lookup('env','RANCHER_ENV_PROD_SECRET_KEY') }}"

http_proxy: "{{ lookup('env','PROD_HTTP_PROXY') }}"
https_proxy: "{{ lookup('env','PROD_HTTPS_PROXY') }}"