<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\Transaction\Subscriber\CreateConsolidatedTransaction\CreateConsolidatedTransactionSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/BaseConstraint.php';
include_once $this->targetDirs[3].'/vendor/justinrainbow/json-schema/src/JsonSchema/Validator.php';
include_once $this->targetDirs[3].'/src/Domain/Utility/Validator/ValidatorInterface.php';
include_once $this->targetDirs[3].'/src/Domain/Utility/Validator/JsonValidator.php';
include_once $this->targetDirs[3].'/src/Domain/Transaction/Subscriber/CreateConsolidatedTransaction/CreateConsolidatedTransactionSubscriber.php';

return $this->privates['App\Domain\Transaction\Subscriber\CreateConsolidatedTransaction\CreateConsolidatedTransactionSubscriber'] = new \App\Domain\Transaction\Subscriber\CreateConsolidatedTransaction\CreateConsolidatedTransactionSubscriber(new \App\Domain\Utility\Validator\JsonValidator(($this->targetDirs[3].'/vendor/tsi-library/consolidated-transaction/schemas'), 'TransactionMessageRequest.json', new \JsonSchema\Validator()), ($this->privates['Tsi\Transaction\Hydrator\ConsolidatedTransaction\ConsolidatedTransactionHydratorInterface'] ?? $this->load(__DIR__.'/getConsolidatedTransactionHydratorInterfaceService.php')), ($this->privates['App\Domain\Transaction\Service\TransactionService'] ?? $this->load(__DIR__.'/getTransactionServiceService.php')));
