<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\Transaction\Dispatcher\TransactionEventDispatcherInterface' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/Transaction/Dispatcher/TransactionEventDispatcherInterface.php';
include_once $this->targetDirs[3].'/src/Domain/Transaction/Dispatcher/TransactionEventDispatcherSymfony.php';

return $this->privates['App\Domain\Transaction\Dispatcher\TransactionEventDispatcherInterface'] = new \App\Domain\Transaction\Dispatcher\TransactionEventDispatcherSymfony(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
