<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Tsi\Transaction\Hydrator\ConsolidatedTransaction\ConsolidatedTransactionHydratorInterface' shared autowired service.

include_once $this->targetDirs[3].'/vendor/tsi-library/consolidated-transaction/src/Transaction/Hydrator/Merchant/MerchantHydratorInterface.php';
include_once $this->targetDirs[3].'/vendor/tsi-library/consolidated-transaction/src/Transaction/Hydrator/Merchant/MerchantHydrator.php';
include_once $this->targetDirs[3].'/vendor/tsi-library/consolidated-transaction/src/Transaction/Hydrator/Outlet/OutletHydratorInterface.php';
include_once $this->targetDirs[3].'/vendor/tsi-library/consolidated-transaction/src/Transaction/Hydrator/Outlet/OutletHydrator.php';
include_once $this->targetDirs[3].'/vendor/tsi-library/consolidated-transaction/src/Transaction/Hydrator/Customer/CustomerHydratorInterface.php';
include_once $this->targetDirs[3].'/vendor/tsi-library/consolidated-transaction/src/Transaction/Hydrator/Customer/CustomerHydrator.php';
include_once $this->targetDirs[3].'/vendor/tsi-library/consolidated-transaction/src/Transaction/Hydrator/Card/CardHydratorInterface.php';
include_once $this->targetDirs[3].'/vendor/tsi-library/consolidated-transaction/src/Transaction/Hydrator/Card/CardHydrator.php';
include_once $this->targetDirs[3].'/vendor/tsi-library/consolidated-transaction/src/Transaction/Hydrator/Voucher/VoucherHydratorInterface.php';
include_once $this->targetDirs[3].'/vendor/tsi-library/consolidated-transaction/src/Transaction/Hydrator/Voucher/VoucherHydrator.php';
include_once $this->targetDirs[3].'/vendor/tsi-library/consolidated-transaction/src/Transaction/Hydrator/ConsolidatedTransaction/ConsolidatedTransactionHydratorInterface.php';
include_once $this->targetDirs[3].'/vendor/tsi-library/consolidated-transaction/src/Transaction/Hydrator/ConsolidatedTransaction/ConsolidatedTransactionHydrator.php';

return $this->privates['Tsi\Transaction\Hydrator\ConsolidatedTransaction\ConsolidatedTransactionHydratorInterface'] = new \Tsi\Transaction\Hydrator\ConsolidatedTransaction\ConsolidatedTransactionHydrator(new \Tsi\Transaction\Hydrator\Merchant\MerchantHydrator(), new \Tsi\Transaction\Hydrator\Outlet\OutletHydrator(), new \Tsi\Transaction\Hydrator\Customer\CustomerHydrator(), new \Tsi\Transaction\Hydrator\Card\CardHydrator(), new \Tsi\Transaction\Hydrator\Voucher\VoucherHydrator());
