<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Rqms\Statistics\Outlets\IndexController' shared autowired service.

include_once $this->targetDirs[3].'/src/Infrastructure/NoSqlDatabase/PipelineBuilder/Statistic/TotalAmountPerOutletForPeriodPipelineBuilderInterface.php';
include_once $this->targetDirs[3].'/src/Infrastructure/NoSqlDatabase/PipelineBuilder/Statistic/TotalAmountPerOutletForPeriodPipelineBuilder.php';
include_once $this->targetDirs[3].'/src/Domain/Transaction/Repository/Statistics/Outlets/OutletStatisticRepositoryInterface.php';
include_once $this->targetDirs[3].'/src/Domain/Transaction/Repository/Statistics/Outlets/OutletStatisticRepository.php';
include_once $this->targetDirs[3].'/src/Domain/Transaction/Service/Statistics/Outlets/OutletStatisticServiceInterface.php';
include_once $this->targetDirs[3].'/src/Domain/Transaction/Service/Statistics/Outlets/OutletStatisticService.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ServiceLocator.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/Rqms/Statistics/Outlets/IndexController.php';

$this->services['App\Controller\Rqms\Statistics\Outlets\IndexController'] = $instance = new \App\Controller\Rqms\Statistics\Outlets\IndexController(new \App\Domain\Transaction\Service\Statistics\Outlets\OutletStatisticService(new \App\Domain\Transaction\Repository\Statistics\Outlets\OutletStatisticRepository(($this->privates['transaction_collection'] ?? $this->load(__DIR__.'/getTransactionCollectionService.php')), new \App\Infrastructure\NoSqlDatabase\PipelineBuilder\Statistic\TotalAmountPerOutletForPeriodPipelineBuilder())));

$instance->setContainer(($this->privates['service_locator.aqxUcvZ'] ?? $this->load(__DIR__.'/getServiceLocator_AqxUcvZService.php'))->withContext('App\\Controller\\Rqms\\Statistics\\Outlets\\IndexController', $this));

return $instance;
