<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.aqxUcvZ' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ServiceLocator.php';

return $this->privates['service_locator.aqxUcvZ'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('http_kernel' => function () {
    return ($this->services['http_kernel'] ?? $this->getHttpKernelService());
}, 'request_stack' => function () {
    return ($this->services['request_stack'] ?? $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack());
}, 'router' => function () {
    return ($this->services['router'] ?? $this->getRouterService());
}));
