<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Domain\Transaction\Service\TransactionService' shared autowired service.

include_once $this->targetDirs[3].'/src/Domain/Transaction/Repository/TransactionRepositoryInterface.php';
include_once $this->targetDirs[3].'/src/Domain/Transaction/Repository/TransactionRepository.php';
include_once $this->targetDirs[3].'/src/Domain/Transaction/Service/TransactionServiceInterface.php';
include_once $this->targetDirs[3].'/src/Domain/Transaction/Service/TransactionService.php';

return $this->privates['App\Domain\Transaction\Service\TransactionService'] = new \App\Domain\Transaction\Service\TransactionService(new \App\Domain\Transaction\Repository\TransactionRepository(($this->privates['Tsi\Transaction\Hydrator\ConsolidatedTransaction\ConsolidatedTransactionHydratorInterface'] ?? $this->load(__DIR__.'/getConsolidatedTransactionHydratorInterfaceService.php')), ($this->privates['transaction_collection'] ?? $this->load(__DIR__.'/getTransactionCollectionService.php'))), ($this->privates['App\Domain\Transaction\Dispatcher\TransactionEventDispatcherInterface'] ?? $this->load(__DIR__.'/getTransactionEventDispatcherInterfaceService.php')));
