<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'transaction_collection' shared autowired service.

include_once $this->targetDirs[3].'/vendor/mongodb/mongodb/src/Client.php';
include_once $this->targetDirs[3].'/src/Infrastructure/NoSqlDatabase/Client/NoSqlDatabaseClientInterface.php';
include_once $this->targetDirs[3].'/src/Infrastructure/NoSqlDatabase/Client/MongoDbClient.php';
include_once $this->targetDirs[3].'/src/Infrastructure/NoSqlDatabase/Collection/Factory/MongoDbCollectionFactory.php';
include_once $this->targetDirs[3].'/src/Infrastructure/NoSqlDatabase/Collection/NoSqlDatabaseCollectionInterface.php';
include_once $this->targetDirs[3].'/src/Infrastructure/NoSqlDatabase/Collection/MongoDbCollection.php';

return $this->privates['transaction_collection'] = (new \App\Infrastructure\NoSqlDatabase\Collection\Factory\MongoDbCollectionFactory(new \App\Infrastructure\NoSqlDatabase\Client\MongoDbClient(new \MongoDB\Client($this->getEnv('MONGO_DB_URI')))))->collection('transactions', 'transactions');
