version: "3.2"
services:
  composer:
    build:
      context: ./../../application
      dockerfile: ./infrastructure/docker/composer/Dockerfile
    volumes:
      - type: volume
        source: ./../../application
        target: /var/www/html
    entrypoint:
      - composer
      - -n
      - update