<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWQCUXaD\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWQCUXaD/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWQCUXaD.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWQCUXaD\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWQCUXaD\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'WQCUXaD',
    'container.build_id' => 'ac507341',
    'container.build_time' => 1522247725,
));
